---
title: "R_Plyler_Ch2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Table2.3}
#### Table 2.3 
getwd()
housing_data <- read.csv("C:/Users/randa/Dropbox/Masters/Winter/TBANLT 560 Data Mining/Module1/WestRoxbury.csv", header = TRUE)  # load data
dim(housing_data)  # find the dimension of data frame
head(housing_data)  # show the first six rows
#View(housing_data)  # show all the data in a new tab
names(housing_data)
```


```{r TestingOfVariables, echo=FALSE}
housing_data[1:10, 1]  # show the first 10 rows of the first column only
housing_data[1:10, ]  # show the first 10 rows of each of the columns 
housing_data[5, 1:10]  # show the fifth row of the first 10 columns
housing_data[5, c(1:2, 4, 8:10)]  # show the fifth row of some columns
housing_data[, 1]  # show the whole first column
housing_data$TOTAL.VALUE  # a different way to show the whole first column
housing_data$TOTAL.VALUE[1:10]  # show the first 10 rows of the first column
length(housing_data$TOTAL.VALUE)  # find the length of the first column
mean(housing_data$TOTAL.VALUE)  # find the mean of the first column
summary(housing_data)  # find summary statistics for each column
```

```{r Sampling_Table2.4}
# random sample of 5 observations
SampleA <- sample(row.names(housing_data), 5)
housing_data[SampleA,]

# oversample houses with over 10 rooms
SampleA <- sample(row.names(housing_data), 5, prob = ifelse(housing_data$ROOMS>10, 0.9, 0.01))
housing_data[SampleA,]

```

```{r Table2.5}
names(housing_data)  # print a list of variables to the screen.
t(t(names(housing_data)))  # print the list in a useful column format TRANSPOSES USING THE LETTER T IN R
colnames(housing_data)[1] <- c("TOTAL_VALUE")  # change the first column'SampleA name

class(housing_data$REMODEL) # REMODEL is a factor variable
class(housing_data[ ,14]) # Same.

levels(housing_data[, 14])  # It can take one of three levels
class(housing_data$BEDROOMS)  # BEDROOMS is an integer variable
class(housing_data[, 1])  # Total_Value is a numeric variable



```

```{r Table2.6}
library(dummies)
housing_data <- dummy.data.frame(housing_data, sep = ".")
names(housing_data)
housing_data

```

```{r Table2.7}
# To illustrate missing data procedures, we first convert a few entries for 
# bedrooms to NA'SampleA. Then we impute these missing values using the median of the 
# remaining values.
rows.to.missing <- sample(row.names(housing_data), 10)
housing_data[rows.to.missing,]$BEDROOMS <- NA
summary(housing_data$BEDROOMS)  # Now we have 10 NA'SampleA and the median of the 

# remaining values is 3.
# replace the missing values using the median of the remaining values.
# use median() with na.rm = TRUE to ignore missing values when computing the median.
housing_data[rows.to.missing,]$BEDROOMS <- median(housing_data$BEDROOMS, na.rm = TRUE)
summary(housing_data$BEDROOMS) 

```

```{r Table2.9}
#### Table 2.9
# use set.seed() to get the same partitions when re-running the R code.
set.seed(1)
```

```{r Table2.1}
## partitioning into training (60%) and validation (40%)
# randomly sample 60% of the row IDs for training; the remaining 40% serve as
# validation
train.rows <- sample(rownames(housing_data), dim(housing_data)[1]*0.6)
#as.integer(train.rows)
class(train.rows)

# collect all the columns with training row ID into training set:
train.data <- housing_data[train.rows, ]

# assign row IDs that are not already in the training set, into validation 
valid.rows <- setdiff(rownames(housing_data), train.rows) 
valid.data <- housing_data[valid.rows, ]
itrain.rows<- as.integer(train.rows)

# alternative code for validation (works only when row names are numeric): 
# collect all the columns without training row ID into validation set 
valid.data <- housing_data[-itrain.rows, ] # does not work in this case

## partitioning into training (50%), validation (30%), test (20%)
# randomly sample 50% of the row IDs for training
train.rows <- sample(rownames(housing_data), dim(housing_data)[1]*0.5)

# sample 30% of the row IDs into the validation set, drawing only from records
# not already in the training set
# use setdiff() to find records not already in the training set
valid.rows <- sample(setdiff(rownames(housing_data), train.rows), 
                     dim(housing_data)[1]*0.3)

# assign the remaining 20% row IDs serve as test
test.rows <- setdiff(rownames(housing_data), union(train.rows, valid.rows))

# create the 3 data frames by collecting all columns from the appropriate rows 
train.data <- housing_data[train.rows, ]
valid.data <- housing_data[valid.rows, ]
test.data <- housing_data[test.rows, ]
names(train.data)
```

```{r Table2}

#### Table 2.11
regression_model <- lm(TOTAL_VALUE ~ .-TAX, data = housing_data, subset = train.rows) # remove variable "TAX"

summary(regression_model)

training_residual_values <- data.frame(train.data$TOTAL_VALUE, regression_model$fitted.values, regression_model$residuals)

head(training_residual_values)
str(regression_model)
str(train.data)
length(regression_model$fitted.values)
length(regression_model$residuals)
length(train.data$TOTAL.VALUE)

RandyRegression <- lm(TOTAL_VALUE ~ LOT.SQFT + YR.BUILT + GROSS.AREA + LIVING.AREA + FLOORS, data = train.data)
summary(regression_model)
summary(RandyRegression)
```

```{r Table2.12}

prediction_model <- predict(regression_model, newdata = valid.data)
validation_model <- data.frame(valid.data$TOTAL_VALUE, prediction_model, residuals = valid.data$TOTAL_VALUE - prediction_model)
head(validation_model)

```

```{r Table2.13}

#### Table 2.13
library(forecast)
# compute accuracy on training set
accuracy(regression_model$fitted.values, train.data$TOTAL_VALUE)
# compute accuracy on prediction set
prediction_model <- predict(regression_model, newdata = valid.data)
accuracy(prediction_model, valid.data$TOTAL_VALUE)
```



